### ISSUE TITLE
Expanding the upper limit to 31st Dec 2020

### ISSUE THREAD

**Issue by kcsamir** [worldpopulation/population.io#103]
In the current model, the system does not allow you to enter a birthday after December 2014 (see below). If you enter the birthday 1 January 2015, it does not work. I think some restriction was applied earlier due to data limitation, now we have longer time series, so I suggest to expand the allowable birthday to 2020.

**Comment by b-g** [comment]
Hi @kcsamir, thanks for the TODO! However I think this is rather a backend issue e.g. 
http://api.population.io:80/1.0/wp-rank/2020-12-30/male/United%20Kingdom/today/
http://api.population.io/#!/wp-rank/worldPopulationRankToday

I guess this limit is somewhere hardcoded on the backend side ... hence can you please investigate this with Andrew? 

(please note there are two issue trackers front vs. backend, this issue should rather go into https://github.com/worldpopulation/population.io-api/ :)

**Comment by megawebmaster** [comment]
Fixed - works up to "today" as agreed.
