### ISSUE TITLE
Introduce FR Translation

### ISSUE THREAD

**Issue by b-g** [worldpopulation/population.io#105]
Here is the file from the translator:
[POPIO_FR_V2.txt](https://github.com/worldpopulation/population.io/files/5187/POPIO_FR_V2.txt)

**Comment by nikolaskaramuca** [comment]
In that file array keys are also translated so app is ignoring translations, wrong quotes are used so JSON structure is broken and even some angular vars are translated so app is crashing. Here is the corrected version. Please don't edit/update old one!

**Comment by nikolaskaramuca** [comment]
{
  "LOCAL_COUNTRY": "Pays",
  "LOCAL_WORLD": "Monde",
  "LOCAL_ASIA": "Asie",
  "LOCAL_EUROPE": "Europe",
  "LOCAL_AFRICA": "Afrique",
  "LOCAL_AFRICA": "Afrique",
  "LOCAL_NORTH_AMERICA": "Amérique du Nord",
  "LOCAL_SOUTH_AMERICA": "Amérique du Sud",
  "LOCAL_OCEANIA": "Océanie",

  "LOCAL_DAY": "Jour",
  "LOCAL_MONTH": "Mois",
  "LOCAL_YEAR": "Année",
  "LOCAL_YEARS": "Années",

  "LOCAL_FEMALE": "Féminin",
  "LOCAL_MALE": "Masculin",

  "HEADER_TITLE": "Le projet de la population mondiale",
  "HEADER_MENU_ABOUT": "A propos",
  "HEADER_MENU_METHODOLOGY": "Méthodologie",
  "HEADER_MENU_API": "API",

  "SHARE_TED_TALK": "Regarder la conférence TED",
  "SHARE_TEXT": "Partager",

  "HOME_WORLD_CLOCK": "Décompte actuel<br> de la population<br> mondiale<br>",
  "HOME_TEXT_BIG": "Quel est ma place dans la population mondiale? Combien de temps me reste-t-il à vivre?",
  "HOME_TEXT_SMALL": "Le parcours de votre vie en chiffres et dates!<br> Veuillez entrer votre date de naissance, votre pays de naissance et votre sexe à la naissance:",
  "HOME_FORM_SUBMIT": "Calculer",

  "ABOUT_INTRO": "le but de <i>Population.io</i> est de rendre la démographie – l´étude  des populations humaines – accessible au grand public. Nous croyons que les données démographiques peuvent jouer un rôle important dans la compréhension des développements sociaux et économiques d’aujourd’hui. Nous espérons aussi que les personnes de tout âge et du monde entier découvriront une nouvelle perspective sur leur vies et sur leur propre place dans le monde d’aujourd’hui et de demain.",
  "ABOUT_CREDITS_CORE": "<i>Population.io</i> a été développé par <a href='http://blogs.worldbank.org/team/wolfgang-fengler'>Wolfgang Fengler</a> (wfengler AT worldbank DOT org, <a href='http://twitter.com/wolfgangfengler'>@wolfgangfengler</a>), ensemble avec <a href='http://www.iiasa.ac.at/web/home/research/researchPrograms/WorldPopulation/Staff/K-C-Samir.en.html'>K.C. Samir</a> (<a href='https://twitter.com/kcsamir'>@kcsamir</a>) et <a href='http://benedikt-gross.de/'>Benedikt Groß</a> (<a href='https://twitter.com/bndktgrs'>@bndktgrs</a>).",
  "ABOUT_CREDITS_SUPPORTED": "Ce projet a bénéficié du soutien généreux <a href='http://data.worldbank.org/'>World Bank Data Group</a> et la <a href='http://www.iiasa.ac.at/'>International Institute for Applied Systems Analysis</a> (IIASA). L’équipe apprécie également le partenariat avec la Division de la population du Département des affaires économiques et sociales des Nations Unies, qui a fourni les estimations et les projections sur lesquelles notre modèle est basé (voir la méthodologie). Et tout a été rendu possible grâce aux contributions volontaires et généreuses des personnes suivants (en ordre chronologique inversé):",
  "ABOUT_CREDITS_CONTRIBUTERS": "<a href='http://lukaszcaputa.eu/'>Łukasz Caputa</a> (développement et conseil applications mobiles), Alexandra Colón et Laura Jaramillo (traductions en espagnol), <a href='http://trojniak.net/'>Rafał Trójniak</a> (backend/cloud computing), <a href='http://andrewwhitby.com/'>Andrew Whitby</a> (algorithmes et mise en œuvre en Python), <a href='http://www.wu.ac.at/sozio/institut/personalextern/tkriszti'>Tamás Krisztin</a> (algorithmes et mise en œuvre en Python), <a href='http://jk-lee.com/'>Joey Lee</a> (cartes , SIG et R à portage Python), <a href='http://www.47nord.de/'>47 Nord</a> (mises en page et la mise en œuvre de la version α) et Emi Suzuki (données démographiques).",
  "ABOUT_DISCLAIMER": "Les valeurs utilisées dans l'application ont été calculées par l'équipe de <i>Population.io</i> sur la base des différentes séries de projections et d'estimations publiées dans le </a> <a href='http://esa.un.org/wpp/'> World Population Prospects, révision 2012 de la <a href='http://www.un.org/en/development/desa/population/' Division de la population de l'ONU. Ils reflètent les estimations les plus actuelles pour chaque pays ainsi que pour le monde entier. Il reste des insuffisances au niveau de la qualité des données, en particulier pour les pays en développement. Il est également important de noter que, particulièrement pour la projection de l’espérance de vie, le système calcule les points médians en fonction d'une estimation de probabilités (voir la section sur la méthodologie).  <i>Population.io</i> prend en compte trois facteurs qui influencent l’espérance de vie: l'âge, le sexe et le pays de naissance/résidence. Cependant, l'espérance de vie dépend également de nombreux autres facteurs et de développements futurs, dont certains sont imprévisibles.<br> <i>Population.io</i> n’assume aucune responsabilité pour l'exactitude des données et investira dans la mise à jour du système pour élargir la base de données et affiner les modèles.",
  "ABOUT_DISCLAIMER_TITLE": "Avertissement",

  "METHODOLOGY_INTRO": "<i>Population.io</i> utilise des données démographiques officielles produites par les Nations Unies et publiées dans les Perspectives de la population mondiale (World Population Prospects, voir les sources de données pour plus de détails) dont la plupart est disponible dans les cycles annuels ou de 5 ans. <i>Population.io</i> utilise les estimations passées pour les années 1950 à 2010 et la projection de la population moyenne jusqu'à 2100 et interpole la distribution pour chaque jour pour le monde entier ainsi que pour 200 pays (à l'exception de quelques pays très peu peuplés) et utilise les estimations et les projections des tables de mortalité de l’ONU pour interpoler l'espérance de vie individuelle par date et lieu de naissance.<br><br> Pour plus d’informations, veuillez consulter notre <a href='https://github.com/worldpopulation/population.io-api/tree/master/modeling'>Methodology/Modeling</a> page.",
  "METHODOLOGY_TITLE": "Méthodologie",

  "API_INTRO": "Toutes les données que vous voyez sur <i>population.io</i> viennent d'une interface de programmation (API) qui est bien documenté avec des détails sur les méthodes et les sources des données utilisées ici:<br><br> <a href='http://api.population.io' target='_blank'>api.population.io</a><br><br> Le code source de ce site et l'API sont également disponibles sur: <a href='https://github.com/worldpopulation/'>github.com/worldpopulation</a> et les développeurs sont cordialement invités à construire à la fois sur l'application et l'API.",

  "SUMMARY_INTRO": "Faites-vous partie des plus jeunes ou des plus âgés? Vous êtes la <span>{{val1}}</span> personne vivante sur la planète. Cela signifie que vous êtes <span>plus âgé que {{val2}}%</span> de la population mondiale et <span>plus âgé que {{val3}}%</span> que toutes les personnes en<span>{{val4}}</span>.",
  "SUMMARY_WORLD": "Monde",
  "SUMMARY_PEOPLE_YOUNGER": "Personnes plus jeunes que vous  (",
  "SUMMARY_PEOPLE_OLDER": "Personnes moins jeunes que vous (",
  "SUMMARY_CITIZEN": "Vous, en tant que citoyen <br>de <span>{{region || profile.country}}</span>",
  "SUMMARY_CHART_AXIS_Y": "Personnes",
  "SUMMARY_CHART_AXIS_X": "Age",

  "BROWSER_WARNING_TITLE":"Alerte Navigateur",
  "BROWSER_WARNING_INTRO":"La version de votre navigateur est trop ancienne pour bien visualiser ce site. S'il vous plaît veuillez télécharger l'un de ces navigateurs qui sont à jour, gratuits et excellents.",

  "MILESTONES_INTRO": "Quelles sont les grandes étapes dans votre vie par rapport à la population mondiale? Votre prochaine étape importante est le <span>{{val1}}</span> où vous serez la <span>{{val2}} milliardième</span> personne vivante dans le monde.",
  "MILESTONES_NOW": "Aujurd'hui",
  "MILESTONES_TITLE_AGE_DISTRIBUTION": "Répartition par âge",
  "MILESTONES_TIMELINE": "Chronologie (projections)",
  "MILESTONES_MILESTONE_LIFE_EXPECTANCY" : "Votre espérance de vie projetée en ",
  "MILESTONES_MILESTONE_1_BILLION": "Milliardième personne",
  "MILESTONES_MILESTONE_2_BILLION": "2 milliardième personne",
  "MILESTONES_MILESTONE_3_BILLION": "3 milliardième personne",
  "MILESTONES_MILESTONE_4_BILLION": "4 milliardième personne",
  "MILESTONES_MILESTONE_5_BILLION": "5 milliardième personne",
  "MILESTONES_MILESTONE_6_BILLION": "6 milliardième personne",
  "MILESTONES_MILESTONE_7_BILLION": "7 milliardième personne",
  "MILESTONES_MILESTONE_8_BILLION": "8 milliardième personne",
  "MILESTONES_MILESTONE_9_BILLION": "9 milliardième personne",
  "MILESTONES_MILESTONE_10_BILLION": "10 milliardième personne",
  "MILESTONES_MILESTONE_11_BILLION": "11 milliardième personne",
  "MILESTONES_MILESTONE_NOW": "Aujourd'hui",
  "MILESTONES_MILESTONE_18": "Vous avez 18 ans!",
  "MILESTONES_MILESTONE_BORN": "Naissance",
  "MILESTONES_CHART_AXIS_Y": "Personnes",
  "MILESTONES_CHART_AXIS_X": "Âge",
  "MILESTONES_CHART_POINTER": "Votre âge",

  "BIRTHDAYS_INTRO": "Saviez-vous que vous partagez votre anniversaire avec environ<span>{{sharedDay}}</span> personnes à travers le monde et qu'environ<span>{{sharedHour}}</span> personnes sont nées dans la même heure?",
  "BIRTHDAYS_TITLE_CONTINENTAL": "Statistiques<br>continentales",
  "BIRTHDAYS_TITLE_WORLD": "Pays avec le plus grand nombre<br>d'anniversaires",
  "BIRTHDAYS_SWITCH_LABEL": "Anniversaires en:",

  "EXPECTANCY_INTRO": "Et si vous viviez aujourd'hui dans un pays différent ou avec l'espérance de vie d'une autre époque ? Combien de temps vous resterait-t-il à vivre?",
  "EXPECTANCY_MAP_POINTER": "{{year}}<br> années à vivre<br> en {{pays}}<br><br> Nous estimons que vous vivrez<br>  jusqu'à l'âge de {{age}} années<br> {{date}}",
  "EXPECTANCY_MAP_POINTER_1": "années à vivre",
  "EXPECTANCY_MAP_POINTER_2": "en ",
  "EXPECTANCY_MAP_POINTER_3": "Nous estimons que vous vivrez",
  "EXPECTANCY_MAP_POINTER_4": "jusqu'à l'âge de ",
  "EXPECTANCY_MAP_POINTER_5": "années",

  "DEATH_INTRO": "Nous estimons que vous vivrez jusqu'au <span>{{dodWorld}}</span> si vous étiez un citoyen moyen du monde. Alors qu’en <span>{{pays}}</span> vous vivrez jusqu'au <span>{{dodPays}}</span>.",
  "DEATH_MORTALITY_DISTRIBUTION": "Répartition de la mortalité",
  "DEATH_CHANCES_OF_DYING": "Chances de mourir",
  "DEATH_CHART_AXIS_Y": "Chances de mourir cumulatifs",
  "DEATH_CHART_AXIS_X": "Âge",
  "DEATH_CHART_YOUR_AGE": "Votre Âge",
  "DEATH_EXPECTANCY_TITLE": "Espérance de vie projetée",
  "DEATH_EXPECTANCY_TXT_WORLD": "Nous estimons que vous vivrez </br><span>{{remainingLifeWorldInYears}} ans</span> en tant que citoyen de <span>World</span>",
  "DEATH_EXPECTANCY_TXT_DIFFERENCE": "Votre vie sera d'environ <span>{{soMuchToDo}}</span> que la moyenne mondiale pour environ<span>{{differenceInUnits}}</span>",
  "DEATH_EXPECTANCY_TXT_COUNTRY": "Nous estimons que vous allez vivre </br><span>{{remainingLifeCountryInYears}} ans</span> en tant que citoyen de<span>{{pays}}</span>",
  "DEATH_EXPECTANCY_TXT_SHORTER": "plus courte",
  "DEATH_EXPECTANCY_TXT_LONGER": "plus longue",

  "FOOTER_SIGNUP_TITLE": "Tenez moi au courant",
  "FOOTER_SIGNUP_TXT": "Envoyez-moi une mise à jour tous les ans le jour de mon anniversaire <br>!",
  "FOOTER_ADD_TO_CALENDAR_TITLE": "Ajouter vote date de décès<br> à votre calendrier",
  "FOOTER_MORE_TITLE": "En savoir plus",
  "FOOTER_MORE_CONTACT": "Contact",
  "FOOTER_MORE_API": "API",
  "FOOTER_SHARE_TITLE": "Partager",


  "MONTH1": "janvier",
  "MONTH2": "février",
  "MONTH3": "mars",
  "MONTH4": "avril",
  "MONTH5": "mai",
  "MONTH6": "juin",
  "MONTH7": "juillet",
  "MONTH8": "août",
  "MONTH9": "septembre",
  "MONTH10": "octobre",
  "MONTH11": "novembre",
  "MONTH12": "décembre",

  "UNIT_DAYS": "jours",
  "UNIT_YEAR": "an",
  "UNIT_YEARS": "ans",

  "BIRTHDAY_SHARED": "anniversaires partagés",

  "ORDINAL_NUMBER_1": "1er",
  "ORDINAL_NUMBER_2": "2ème",
  "ORDINAL_NUMBER_3": "3ème",
  "ORDINAL_NUMBER_4": "4ème",
  "ORDINAL_NUMBER_5": "5ème",
  "ORDINAL_NUMBER_6": "6ème",
  "ORDINAL_NUMBER_7": "7ème"
}

**Comment by nikolaskaramuca** [comment]
Had to paste it since github won't allow me to attach files to your project, will be commited to repo...

**Comment by b-g** [comment]
Thanks! 👍 Sorry for the mess, didn't check the file when I got it back.
