### ISSUE TITLE
Introduce ID (Bahasa Indonesia) translation

### ISSUE THREAD

**Issue by b-g** [worldpopulation/population.io#108]
Here is the file from the translator ... please double check the language code.
[ID.json.txt](https://github.com/worldpopulation/population.io/files/19205/ID.json.txt)

**Comment by LukaszCaputa** [comment]
[Population.io inputs.pptx](https://github.com/worldpopulation/population.io/files/153319/Population.io.inputs.pptx)
The translation is not yet ready @nikolaskaramuca please see attached file with comments from some Indonesian native speaker
