### ISSUE TITLE
Milestones: are no longer clickable

### ISSUE THREAD

**Issue by b-g** [worldpopulation/population.io#150]
The milestones are not longer clickable (OSX Chrome / Safari) on my end :(
Please check and confirm.
http://population.io/#/1984/03/23/male/Germany/milestones
<img width="1481" alt="screen shot 2016-03-23 at 17 58 21" src="https://cloud.githubusercontent.com/assets/480224/13993504/f7ebc08a-f120-11e5-8073-b0e38fd897c1.png">

**Comment by LukaszCaputa** [comment]
@megawebmaster can you take a look if this bug was caused by recent refactoring ?

**Comment by megawebmaster** [comment]
Unfortunately it was caused by my changes, but it was the extension of available milestones - I cleared invalid DOM node and it caused it to be overlapping the milestones area. Fixed.
