### ISSUE TITLE
Values below zero for old people

### ISSUE THREAD

**Issue by LukaszCaputa** [worldpopulation/population.io#178]
For given url
http://population.io/#/1920/1/1/female/United%20Kingdom/summary
two values are below zero:

- -171days

 days
![screen shot 2016-06-14 at 22 48 31](https://cloud.githubusercontent.com/assets/6463684/16060185/ce5dffe2-3286-11e6-9a55-e9928d29f2fa.png)

- -619.891people older than you

![screen shot 2016-06-14 at 23 20 09](https://cloud.githubusercontent.com/assets/6463684/16060191/d0ede060-3286-11e6-9e92-9c899e6904fb.png)

**Comment by megawebmaster** [comment]
Fixed in my branch https://github.com/megawebmaster/population.io/tree/bug-178 which waits for another PR to be merged and released before.
