### ISSUE TITLE
Summary Page: tickers are in/de-cremented wrongly

### ISSUE THREAD

**Issue by b-g** [worldpopulation/population.io#84]
http://population.io/#/1974/03/08/male/Nepal/summary

The number of person younger than me are ticking +7 every second and those older than me is ticking -4 per sec. I rechecked the numbers with births and deaths in the UN system(after Wolfgang asked me to check again), then it should be almost +5 and - 2.

And I think we do not need new APIs to correct this.
The solution is to use the API to get my rank today and tomorrow and then interpolate. 

1. get the change in WorldPopTicker per sec (same number as for the Ticker in the first page) 
2. get the rank for today (lets call it myRankToday) and tomorrow (myRankTomorrow) using the already existing APIs and calculate change in  myRankTicker per sec = (myRankTomorrow - myRankToday)/(24x60x30)
3. Increase the YoungerTicker by myRankTicker per sec
4. Decrease the OlderTicker by (WorldPopTicker per sec - myRankTicker per sec)

![screen shot 2015-04-02 at 11 13 17](https://cloud.githubusercontent.com/assets/480224/6961217/71760d5e-d929-11e4-80c9-bc3b9f5f8e40.png)

**Comment by LukaszCaputa** [comment]
Described above solution is already implemented in code - thus is wrong :) People older then you have to be equal to WorldPopulation - PeopleYoungerThenYou.
