### ISSUE TITLE
Optimize CSS for printing out the site

### ISSUE THREAD

**Issue by b-g** [worldpopulation/population.io#85]

**Comment by megawebmaster** [comment]
Well, this is interesting, although I don't know how the page should look in print. Any suggestions?

**Comment by LukaszCaputa** [comment]
Not really. The best would be if you try to print the page. Then you
see that there is a problem. Ideally, it would look like a nice
document you would want to share with a friend, e.g. when you are
invited to his/.her birthday party.

**Comment by megawebmaster** [comment]
OK, but this requires much more work as it requires to:

1. Update
2. Print (to PDF)
3. Think how to fix
4. Go back to 1 ;)
