### ISSUE TITLE
Translation: Menu language selector

### ISSUE THREAD

**Issue by b-g** [worldpopulation/population.io#91]
Please remove the individual languages from the main menu and put them in a dropdown like this:

![screen shot 2015-06-01 at 14 07 15](https://cloud.githubusercontent.com/assets/480224/7912431/a3fc0bb2-0867-11e5-8e38-4881bea9c46f.png)

**Comment by LukaszCaputa** [comment]
i don't know css + jade + *.styl technology good enough to make this happen. Could you take a look at this task Benedikt ?
