### ISSUE TITLE
Translation: Summary, number formating of Billions and rounding of percentages

### ISSUE THREAD

**Issue by b-g** [worldpopulation/population.io#96]
It should be with commas separators like in the old layout. This is correct:
![screen shot 2015-06-05 at 09 03 51](https://cloud.githubusercontent.com/assets/480224/8001147/101f394c-0b63-11e5-8fef-bab981b587b6.png)

**Comment by LukaszCaputa** [comment]
this one is hard because if we feed following line with variable for val1
        h3(translate="SUMMARY_INTRO" translate-values="{val1: rankGlobal, val2: worldYoungerPercentageSimple, val3: countryYoungerPercentageSimple, val4: profile.country }")

with a number then the text will be updated on every number change. But if we provide string by calling filter
$scope.rankGlobalFormatted = $filter('number')($scope.rankGlobal);
then the text is not updated in translation.

**Comment by b-g** [comment]
Then just leave it for now ... I also don't know a solution for this at the moment :(

**Comment by megawebmaster** [comment]
The solution was really simple if you think how Angular filters work.
